import path from 'node:path';
import { definePlugin } from '@toolsync/core/plugins';
import { MarkdownTemplate } from '@toolsync/template';

/// <reference path="./context.d.ts" />

const repoPlugin = definePlugin({
  name: '@repo/toolsync-plugin',
  loadConfig() {
    return {
      config: {
        '@repo/toolsync-plugin': {},
        '@toolsync/builtin/github-actions': {
          workflows: {
            ci: {
              jobs: {
                build: {
                  steps: [
                    {
                      '@update': {
                        id: 'checks',
                        data: {
                          run: 'pnpm turbo check lint test build --continue',
                        },
                      },
                    },
                    {
                      '@insert': {
                        after: 'changesets',
                        data: {
                          name: 'Publish to VSCode Marketplace',
                          run: `if git tag --points-at HEAD | grep tscad-vscode; then
  pnpm --prefix=packages/vscode-extension vscode:publish
else
  echo "No new tscad-vscode release found (tags: '$(git tag --points-at HEAD)')"
fi
`,
                          env: {
                            VSCE_PAT: '${{ secrets.VSCE_PAT }}',
                          },
                        },
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    };
  },
  async setupPackage(package_) {
    if (!package_.isRoot) {
      const { homepage } = package_.packageJson;

      const readme = await MarkdownTemplate.load(path.join(package_.dir, 'README.md'), {
        notice: `Generated by @repo/toolsync-plugin. Do not edit manually, instead run \`toolsync prepare\`.`,
      });

      readme.update({
        section: 'footer',
        insert: 'bottom',
        content: `---

Developed as part of the [tscad](${homepage}) project.
`,
      });

      await readme.save();
    }
  },
});

export default repoPlugin;
