packages:
  - examples/*
  - packages/*
  - apps/*

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - changeset-release/*

onlyBuiltDependencies:
  - '@jscad/cli'
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
