packages:
  - examples/*
  - packages/*
  - apps/*

gitBranchLockfile: true
mergeGitBranchLockfilesBranchPattern:
  - main
  - changeset-release/*

onlyBuiltDependencies:
  - '@jscad/cli'
  - esbuild
