packages:
  - examples/*
  - packages/*
  - apps/*

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - changeset-release/*

onlyBuiltDependencies:
  - '@jscad/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
